controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

test_message:
    path: /api/testMessage
    controller: App\Controller\ProductCardController::testMessage
    methods: GET

create_product:
    path: /create
    controller: App\Controller\ProductCardController::create
    methods: POST

app_auth:
    path: /api/auth
    controller: App\Controller\AuthController::index
    methods: GET

app_register:
    path: api/auth/register
    controller: App\Controller\AuthController::register
    methods: [POST]

app_login:
    path: api/auth/login
    controller: App\Controller\AuthController::login
    methods: [POST]
    
app_logout:
    path: api/auth/logout
    controller: App\Controller\AuthController::logout
    methods: [GET]

get_user_info:
    path: api/auth/user
    controller: App\Controller\AuthController::getUserInfo
    methods: [GET]

product_dashboard:
    path: /admin/product
    controller: App\Controller\Admin\Product\ProductDashboardController::index
category_dashboard:
    path: /admin/category
    controller: App\Controller\Admin\Category\CategoryDashboardController::index